INSERT INTO permissao (descricao, perfil_acesso_id) VALUES
    ('CADASTRAR_LIVRO', 1),
    ('EDITAR_LIVRO', 1),
    ('EXCLUIR_LIVRO', 1),
    ('VISUALIZAR_LIVRO', 1),
    ('CADASTRAR_USUARIO', 1),
    ('EDITAR_USUARIO', 1),
    ('EXCLUIR_USUARIO', 1),
    ('VISUALIZAR_USUARIO', 1),
    ('VISUALIZAR_PROPRIO_USUARIO', 1),
    ('CADASTRAR_PERFIL', 1),
    ('EDITAR_PERFIL', 1),
    ('EXCLUIR_PERFIL', 1),
    ('VISUALIZAR_PERFIL', 1),
    ('CADASTRAR_PERMISSAO', 1),
    ('EDITAR_PERMISSAO', 1),
    ('EXCLUIR_PERMISSAO', 1),
    ('VISUALIZAR_PERMISSAO', 1),
    ('VISUALIZAR_PAINEL_USUARIOS', 1),
    ('VISUALIZAR_PAINEL_LIVROS', 1);

INSERT INTO permissao (descricao, perfil_acesso_id) VALUES
    ('VISUALIZAR_LIVRO', 2),
    ('VISUALIZAR_PROPRIO_USUARIO', 2); 